name: TamaraLyn
favicon: null
layout_spectrum: 0.4329459404107183
typography_spectrum: 0.09646729403175414
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.40225724945776165
  lightness: 0.6336593399755657
  saturation: 0.8514160881750286
  rhythmicContrast: 0.09504173952154815
purpose: []
